### ISSUE TITLE
[Request] New window take the master place

### ISSUE THREAD

**Issue by Cyberdr3am** [windwp/i3-master-slave#1]
Hi,

I whant to do this for long time so thx a lot.

Can you add the possibility of putting all the new windows directly in master as in dwm for example.

Like this all the new open windows will be on the left directly in master and not following the others on the right.

It will be really great

Thx

**Comment by windwp** [comment]
Now if you focus on master and create new window it will swap to master and push another to top stack like dwm.
If you focus on child node of slave then it will not swap it to master

**Comment by Cyberdr3am** [comment]
Thx for the update.

Sometimes when the master closes, a slave also closes it. It may happen that the focus window is not the right one.
When I open applications it is possible that the previous master window remains in master and does not go into slaves.
Finally, if it would be possible for the second open window to switch on its own to master directly without needing the focus.

**Comment by windwp** [comment]
I don't have an issue with close a slave window on master window. Are you open that slave window by command?

You can get a latest version and it have a feature for switch to the previous master by press $Mod+m (nop swap master)
you can swap first window and second window by $Mod + m too

**Comment by Cyberdr3am** [comment]
Yes i use command to close window.

This kill the window or prog focus       [con_id="__focused__" instance="^(?!dropdown_).*$"] kill
This open prog into the terminal on specific workspace     exec --no-startup-id $term -e htop

With the last commit, only the terminal declare in the variable can take the master place when it start.
If i open arandr vlc firefox ... windows go directly into slave whether I focus the master or not

**Comment by windwp** [comment]
I already try to push it on my config but nothing happen
```
 [con_id="focused" instance="^(?!dropdown_).*$"] kill
exec --no-startup-id $term -e htop
```
I update it now you can take master on vlc and firefox too.
I move the config data outside of code.
You need to update your config file 
[config](https://github.com/windwp/i3-master-slave#config)

**Comment by Cyberdr3am** [comment]
After a quick test it seems to me that everything is going very well
Thank you very much for taking the time and creating this.
If I ever see a problem I'll tell you.
