### ISSUE TITLE
[Request] Cycle between master and latest window in stack with mod+shift+m

### ISSUE THREAD

**Issue by Unser395** [windwp/i3-master-slave#3]
Hello !

First, I want to thank you for making this layout, it's great to use. I've only had some issues during the installation and some problems with the slavestack option, but I'll try to report these once I have a bit more time.

Currently, when you press mod+m, the focus changes to the master node. I've used a script in the past that allowed pressing mod+m again to get back to the latest window in the stack layout. I think it could be a nice addition to be able to do that, you could cycle through two windows without having to get back to mod+l or mod+h.

Unfortunately, I'm not a programmer, so I can't help you with that. I don't know how hard that would be to implement as well. Here is the script I was using before, maybe it could help : https://github.com/tenllado/dotfiles/blob/539f5eb3fdc92934673186eb17cbec65e330a0bd/config/i3/scripts/focuscolumn.py

Thanks again for your work and have a nice day !

**Comment by windwp** [comment]
hi
what do you mean about latest window in stack if it is a last focus window then you still can press mod m to swap again or mod +shift+m to focus.

**Comment by Unser395** [comment]
Let's say that I have a master node on the left and three windows on the right.
If I go to the third window on the right and press mod+shift+m, I go to the master node.
But if I press mod+shift+m again, I don't get back to the third window in the stack. I'm still in the master node. That's what I'd like to do.

On the other hand, let's say  I focus the master window. If I swap master window and third window in stack, then pressing mod+shift+m indeed focus the swapped window and I can do that as much as I want, and switch the focus back and forth between the two columns. 
But let's say that that I go to second window in stack now (after having swapped master window and third window), if I press mod+shift+m again while master window is focused, I get back to the third window, not the second one. But maybe it's expected behavior.

I hope I'm clear enough !

**Comment by windwp** [comment]
@Unser395  
hi i upgrade it to fix the first problem it is my mistake when refactor code.
about another problem can you tell me how do you swap it from master to another window ?
the idea of mod+shift+ m is goto master if it  focus on another window and switch it back to another window  if it on master window

_sorry about close issue problem It is closed automatic when i push code reference to this issue_

**Comment by Unser395** [comment]
Hey, thank you very much for fixing that, it's working perfectly now ! 
I was switching with mod+m, but seems like what you did fix the other problem as well !

I hope you have a nice day !

Oh and sorry I just noticed I did a mistake in the thread title, I meant mod+shift+ not mod+m, sorry if it led to some confusion.
