### ISSUE TITLE
[Bug] First window open on workspace (if terminal) is opened as floating

### ISSUE THREAD

**Issue by SoptikHa2** [windwp/i3-master-slave#4]
When I am on empty workspace, have enabled master layout (via `python3 i3_master_layout.py`) and open terminal, it opens as floating window all the time.

Using default i3-master-stack configuration otherwise.

Is it possible to only float windows that were floating by default, eg gpg keypin and so on?

**Comment by windwp** [comment]
please readme  https://github.com/windwp/i3-master-stack#feature
It is a feature when you open another application it will change your first terminal to tiling window

you can change it by update the config file and change to empty terminal or you can update the terminal size and position

https://github.com/windwp/i3-master-stack#config

**Comment by SoptikHa2** [comment]
Thanks!
